### ISSUE TITLE
Citus optimize multi-shard range search queries

### ISSUE THREAD

**Issue by xin-hedera** [hiero-ledger/hiero-mirror-node#5409]
### Problem

Rest API performance tests show citus performs quite worse for multi-shard range search queries and it doesn't scale well with increasing number of virtual users

### Solution

There are multiple approaches we can experiment and they are not mutually exclusive

- [x] #5438
- [x] reduce the number of shards from the default 32 to 16
- [x] add readonly coordinator nodes and spread the read queries
- [x] Add pgbouncer to each node
- [x] add worker nodes / increase the max connections allowed between coordinators and worker nodes

Run the REST performance tests to check if performance improves
